#include "DkimManager.h"

#include <cctype>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <unistd.h>

namespace containercp::mail {

DkimManager::DkimManager(logger::Logger& logger)
    : logger_(logger)
{
}

std::string DkimManager::validate_label(const std::string& label,
                                         const std::string& name) {
    if (label.empty()) {
        return name + " must not be empty";
    }
    for (char c : label) {
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '.' && c != '-') {
            return name + " contains invalid characters";
        }
    }
    return "";
}

std::string DkimManager::generate_key(const std::string& dkim_dir,
                                       const std::string& domain,
                                       const std::string& selector) {
    // Validate inputs before any filesystem operations
    std::string domain_err = validate_label(domain, "Domain");
    if (!domain_err.empty()) {
        logger_.error("DKIM", domain_err + ": " + domain);
        return "";
    }
    std::string sel_err = validate_label(selector, "Selector");
    if (!sel_err.empty()) {
        logger_.error("DKIM", sel_err + ": " + selector);
        return "";
    }

    // Create domain DKIM directory
    std::string domain_dir = dkim_dir + "/" + domain;
    auto mkdir = executor_.run({"mkdir", "-p", domain_dir});
    if (mkdir.exit_code != 0) {
        logger_.error("DKIM", "Failed to create directory: " + mkdir.err);
        return "";
    }

    // Generate 2048-bit RSA private key via CommandExecutor
    std::string priv_path = domain_dir + "/" + selector + ".private";
    auto gen = executor_.run({
        "openssl", "genrsa", "-out", priv_path, "2048"
    });
    if (gen.exit_code != 0) {
        logger_.error("DKIM", "genrsa failed: " + gen.err);
        return "";
    }

    // Extract public key to a uniquely-named temp file (commit mkstemp)
    char pub_tmpl[] = "/tmp/containercp-dkim-pub-XXXXXX";
    int fd = ::mkstemp(pub_tmpl);
    if (fd < 0) {
        logger_.error("DKIM", "Failed to create temp file");
        return "";
    }
    ::close(fd);

    // Shell pipeline: extract public key → DER → base64 → write to temp file.
    // This uses a shell for the pipe operators, which is acceptable because:
    // - domain and selector are validated (alphanumeric, dot, hyphen only)
    // - temp filename is safely generated by mkstemp (unique, non-predictable)
    std::string pipeline =
        "openssl rsa -in " + priv_path + " -pubout 2>/dev/null | "
        "openssl pkey -pubin -outform DER 2>/dev/null | "
        "openssl base64 -A > " + pub_tmpl + " 2>/dev/null";

    int pipe_rc = std::system(pipeline.c_str());

    std::string pubkey_b64;
    if (pipe_rc == 0) {
        std::ifstream in(pub_tmpl);
        std::getline(in, pubkey_b64);
    }
    std::remove(pub_tmpl);

    if (pubkey_b64.empty()) {
        logger_.error("DKIM", "Failed to extract public key");
        return "";
    }

    logger_.info("DKIM", "Key generated for " + domain
                 + " (selector: " + selector + ")");
    return "v=DKIM1; k=rsa; p=" + pubkey_b64;
}

} // namespace containercp::mail
