FROM debian:trixie
RUN apt-get update && apt-get install -y --no-install-recommends \
    rspamd \
    && rm -rf /var/lib/apt/lists/*
COPY docker-entrypoint-rspamd.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-rspamd.sh
EXPOSE 11332 11334
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-rspamd.sh"]
