FROM debian:trixie
RUN apt-get update && apt-get install -y --no-install-recommends \
    dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/mail
EXPOSE 143 993 24
COPY docker-entrypoint-dovecot.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-dovecot.sh
ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dovecot.sh"]
CMD ["dovecot", "-F"]
