import './core/context.js';
import './core/shell.js';
import { registerRoute } from './core/router.js';
import { dashboardPage } from './pages/dashboard.js';
import { sitesPage, siteDetailPage } from './pages/sites.js';
import { domainsPage, domainDetailPage } from './pages/domains.js';
import { databasesPage } from './pages/databases.js';
import { sslPage } from './pages/ssl.js';
import { mailPage, mailDomainPage, mailHealthPage } from './pages/mail.js';
import { webmailPage } from './pages/webmail.js';
import { proxyPage } from './pages/proxy.js';
import { accessPage } from './pages/access.js';
import { backupsPage } from './pages/backups.js';
import { migrationPage } from './pages/migration.js';
import { profilesPage } from './pages/profiles.js';
import { templatesPage } from './pages/templates.js';
import { nodesPage } from './pages/nodes.js';
import { logsPage } from './pages/logs.js';
import { settingsPage } from './pages/settings.js';

registerRoute('dashboard', dashboardPage);
registerRoute('sites', sitesPage);
registerRoute('site-detail', siteDetailPage);
registerRoute('domains', domainsPage);
registerRoute('domain-detail', domainDetailPage);
registerRoute('databases', databasesPage);
registerRoute('ssl', sslPage);
registerRoute('mail', mailPage);
registerRoute('mail-domain', mailDomainPage);
registerRoute('mail-health', mailHealthPage);
registerRoute('webmail', webmailPage);
registerRoute('proxy', proxyPage);
registerRoute('access', accessPage);
registerRoute('backups', backupsPage);
registerRoute('migration', migrationPage);
registerRoute('profiles', profilesPage);
registerRoute('templates', templatesPage);
registerRoute('nodes', nodesPage);
registerRoute('logs', logsPage);
registerRoute('settings', settingsPage);
