import './core/context.js';
import './core/shell.js';
import { registerRoute } from './core/router.js';
import { loadDashboard } from './pages/dashboard.js';
import { loadSites, loadSiteDetail } from './pages/sites.js';
import { loadDomains, loadDomainDetail } from './pages/domains.js';
import { loadDatabases } from './pages/databases.js';
import { loadSsl } from './pages/ssl.js';
import { loadMail, loadMailDomain, loadMailHealth } from './pages/mail.js';
import { loadWebmail } from './pages/webmail.js';
import { loadProxy } from './pages/proxy.js';
import { loadAccess } from './pages/access.js';
import { loadBackups } from './pages/backups.js';
import { loadMigration } from './pages/migration.js';
import { loadProfiles } from './pages/profiles.js';
import { loadTemplates } from './pages/templates.js';
import { loadNodes } from './pages/nodes.js';
import { loadLogs } from './pages/logs.js';
import { loadSettings } from './pages/settings.js';

registerRoute('dashboard', loadDashboard);
registerRoute('sites', loadSites);
registerRoute('site-detail', loadSiteDetail);
registerRoute('domains', loadDomains);
registerRoute('domain-detail', loadDomainDetail);
registerRoute('databases', loadDatabases);
registerRoute('ssl', loadSsl);
registerRoute('mail', loadMail);
registerRoute('mail-domain', loadMailDomain);
registerRoute('mail-health', loadMailHealth);
registerRoute('webmail', loadWebmail);
registerRoute('proxy', loadProxy);
registerRoute('access', loadAccess);
registerRoute('backups', loadBackups);
registerRoute('migration', loadMigration);
registerRoute('profiles', loadProfiles);
registerRoute('templates', loadTemplates);
registerRoute('nodes', loadNodes);
registerRoute('logs', loadLogs);
registerRoute('settings', loadSettings);
